#!/usr/bin/env python3
"""Export a trained MUFFIN model to a standalone C++ header.

The v29pre analysis chain applies the binned fake factor through a JIT-declared
C++ function (declare_fr2d() in closure_v29pre_...py).  This writes the drop-in
replacement: a header with no dependencies that can be handed to
ROOT.gInterpreter.Declare and used inside RDataFrame exactly the same way, so
MUFFIN needs no friend trees and no python in the event loop.

    bash muffin/run.sh export_muffin_cpp.py --tag full --validate

Output: out/muffin_<tag>.h  defining

    double muffin_weight(<features in order>)          the per-event fake factor
    double muffin_weight_boot(int i, <features>)       bootstrap replica i, if exported

and printing the RDataFrame Define() string to use.
"""
import argparse
import glob
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import muffin_common as mc  # noqa: E402
from muffin_model import MuffinModel  # noqa: E402

# how each feature is built from the branches of the analysis trees
BRANCH_EXPR = {
    'tau1decayMode': 'tau1decayMode',
    'ptratio': '(tau1jetPt/std::max(tau1Pt,1.e-6f))',
    'tau1Pt': 'tau1Pt',
    'tau1jetPt': 'tau1jetPt',
    'nsmalljets': 'nsmalljets',
    'nbtags': 'nbtags',
    'tau1Eta': 'tau1Eta',
    'abs_tau1Eta': 'std::fabs(tau1Eta)',
    'tau1Phi': 'tau1Phi',
    'tau1jetDeepFlavB': 'tau1jetDeepFlavB',
    'tau1jetQGL': 'tau1jetQGL',
}


def flatten(model):
    """Booster -> flat node arrays (feature, threshold/leaf, left, right, missing).

    Parsed from the JSON dump, NOT from trees_to_dataframe(): the dataframe
    rounds the split value, and the hist tree builder puts thresholds exactly on
    integer feature values (tau1decayMode < 1, nsmalljets < 5, ...), so a rounded
    threshold sends those events down the wrong branch."""
    dumps = model.bst.get_dump(dump_format='json')
    fidx = {f: i for i, f in enumerate(model.feature_names)}
    feat, thr, left, right, miss, off = [], [], [], [], [], [0]
    for d in dumps:
        tree = json.loads(d)
        nodes, order = {}, []

        def walk(nd):                       # collect nodes by their in-tree id
            nodes[nd['nodeid']] = nd
            order.append(nd['nodeid'])
            for ch in nd.get('children', []):
                walk(ch)
        walk(tree)
        local = {nid: k for k, nid in enumerate(order)}
        base = off[-1]
        for nid in order:
            nd = nodes[nid]
            if 'leaf' in nd:
                feat.append(-1)
                thr.append(float(nd['leaf']))
                left.append(-1); right.append(-1); miss.append(-1)
            else:
                # xgboost's rule is: feature < split_condition -> 'yes'
                feat.append(fidx[nd['split']])
                thr.append(float(nd['split_condition']))
                left.append(base + local[nd['yes']])
                right.append(base + local[nd['no']])
                miss.append(base + local[nd['missing']])
        off.append(len(feat))
    return np.array(feat), np.array(thr), np.array(left), np.array(right), \
        np.array(miss), np.array(off)


def cfloat(v):
    """C++ float literal: %g alone yields '10', and '10f' is not a valid
    constant -- a decimal point has to be there before the suffix."""
    s = '%.9g' % v
    if not any(c in s for c in '.eE'):
        s += '.'
    return s + 'f'


def carr(name, arr, ctype):
    # thresholds and leaves are float32 inside xgboost; emitting them as float
    # keeps the C++ comparison bit-identical to the one the model was built with
    body = ', '.join(cfloat(v) if ctype == 'float' else str(int(v)) for v in arr)
    return '  static const %s %s[%d] = {%s};\n' % (ctype, name, len(arr), body)


def emit(models, tag, feature_names):
    """models: list of (suffix, MuffinModel); the first must be the nominal."""
    ns = 'MUFFIN_%s' % tag.upper().replace('-', '_')
    out = ['// Auto-generated by muffin/export_muffin_cpp.py -- do not edit.',
           '// MUFFIN fake factor for jet->tau_h, v29pre 1tau0l.',
           '// features (in order): %s' % ', '.join(feature_names),
           '#pragma once', '#include <cmath>', '#include <algorithm>', '',
           'namespace %s {' % ns,
           '  static const int NFEAT = %d;' % len(feature_names), '']
    for suf, m in models:
        f, t, l, r, ms, off = flatten(m)
        out.append('  // --- model %s ---' % suf)
        out.append(carr('FEAT_%s' % suf, f, 'int'))
        out.append(carr('THR_%s' % suf, t, 'float'))
        out.append(carr('LEFT_%s' % suf, l, 'int'))
        out.append(carr('RIGHT_%s' % suf, r, 'int'))
        out.append(carr('MISS_%s' % suf, ms, 'int'))
        out.append(carr('OFF_%s' % suf, off, 'int'))
        out.append('  static const int NTREE_%s = %d;' % (suf, len(off) - 1))
        out.append('  static const double B0_%s = %.9g;' % (suf, m.b0))
        out.append('  static const double NORM_%s = %.9g;' % (suf, m.norm))
        out.append('')
    out += [
        '  inline double eval(const float* x, const int* FEAT, const float* THR,',
        '                     const int* LEFT, const int* RIGHT, const int* MISS,',
        '                     const int* OFF, int ntree, double b0, double norm) {',
        '    double m = b0;',
        '    for (int t = 0; t < ntree; ++t) {',
        '      int n = OFF[t];',
        '      while (FEAT[n] >= 0) {',
        '        const float v = x[FEAT[n]];',
        '        n = std::isnan(v) ? MISS[n] : (v < THR[n] ? LEFT[n] : RIGHT[n]);',
        '      }',
        '      m += THR[n];',
        '    }',
        '    if (m < -20.) m = -20.; else if (m > 20.) m = 20.;',
        '    double w = norm * std::exp(m);',
        '    return std::min(std::max(w, 1.e-4), 20.);',
        '  }',
        '}  // namespace', '']

    args = ', '.join('float %s' % f for f in feature_names)
    fill = '    const float x[%d] = {%s};\n' % (
        len(feature_names), ', '.join(feature_names))
    out += ['inline double muffin_weight(%s) {' % args, fill.rstrip('\n'),
            '  return %s::eval(x, %s::FEAT_nominal, %s::THR_nominal, %s::LEFT_nominal,'
            % (ns, ns, ns, ns),
            '                  %s::RIGHT_nominal, %s::MISS_nominal, %s::OFF_nominal,'
            % (ns, ns, ns),
            '                  %s::NTREE_nominal, %s::B0_nominal, %s::NORM_nominal);'
            % (ns, ns, ns),
            '}', '']
    boots = [s for s, _ in models if s.startswith('boot')]
    if boots:
        out += ['inline double muffin_weight_boot(int i, %s) {' % args,
                fill.rstrip('\n'), '  switch (i) {']
        for s in boots:
            out += ['    case %d: return %s::eval(x, %s::FEAT_%s, %s::THR_%s, %s::LEFT_%s,'
                    % (int(s[4:]), ns, ns, s, ns, s, ns, s),
                    '                             %s::RIGHT_%s, %s::MISS_%s, %s::OFF_%s,'
                    % (ns, s, ns, s, ns, s),
                    '                             %s::NTREE_%s, %s::B0_%s, %s::NORM_%s);'
                    % (ns, s, ns, s, ns, s)]
        out += ['  }', '  return muffin_weight(%s);' % ', '.join(feature_names),
                '}', '']
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--tag', default='full')
    ap.add_argument('--bootstrap', type=int, default=0,
                    help='also export the first N bootstrap replicas')
    ap.add_argument('--validate', action='store_true',
                    help='JIT-compile the header and compare with the python model')
    args = ap.parse_args()

    mdir = os.path.join(mc.OUTDIR, 'models')
    nom = MuffinModel.load(os.path.join(mdir, 'muffin_%s_nominal' % args.tag))
    models = [('nominal', nom)]
    for i in range(args.bootstrap):
        pre = os.path.join(mdir, 'muffin_%s_boot%03d' % (args.tag, i))
        if os.path.exists(pre + '_cfg.json'):
            models.append(('boot%d' % i, MuffinModel.load(pre)))
    print('exporting %d model(s): %s' % (len(models), ', '.join(s for s, _ in models)))

    hdr = emit(models, args.tag, nom.feature_names)
    path = os.path.join(mc.OUTDIR, 'muffin_%s.h' % args.tag)
    os.makedirs(mc.OUTDIR, exist_ok=True)
    with open(path, 'w') as fh:
        fh.write(hdr)
    print('wrote %s (%.1f MB)' % (path, os.path.getsize(path) / 1e6))

    print('\nUse it in RDataFrame exactly like declare_fr2d():')
    print("    ROOT.gInterpreter.Declare(open('%s').read())" % path)
    print("    df = df.Define('muffin_weight', 'muffin_weight(%s)')"
          % ', '.join(BRANCH_EXPR[f] for f in nom.feature_names))

    if args.validate:
        import ROOT
        ROOT.gInterpreter.Declare(hdr)
        dr = mc.load_region('DR', verbose=False)
        X = mc.select_features(dr, nom.feature_names)[:2000]
        py = nom.predict(X)
        cpp = np.array([ROOT.muffin_weight(*[float(v) for v in row]) for row in X])
        d = np.abs(cpp - py) / np.maximum(py, 1e-9)
        print('\nvalidation on %d events: max rel. diff %.3e, mean %.3e'
              % (len(py), d.max(), d.mean()))
        assert d.max() < 1e-5, 'C++ and python models disagree'
        print('C++ header reproduces the python model.')


if __name__ == '__main__':
    main()
